### ISSUE TITLE
有问题请留言

### ISSUE THREAD

**Issue by YuleZhang** [YuleZhang/JDComment_Spider#2]

**Comment by bryceustc** [comment]
你好，我想问下爬取过程中，爬取一会儿就报如下错误，请问该怎么解决呢
```
the error is  Expecting value: line 1 column 1 (char 0)
wating---
```

**Comment by YuleZhang** [comment]
京东可能加了一些频繁访问限制，使得request返回得到空页面，因此就会出现上述错误。程序中wating是采取的等待重试，也可以添加动态ip等其他反爬虫策略。

**Comment by YuleZhang** [comment]
> 你好，我想问下爬取过程中，爬取一会儿就报如下错误，请问该怎么解决呢
> 
> ```
> the error is  Expecting value: line 1 column 1 (char 0)
> wating---
> ```

京东可能加了一些频繁访问限制，使得request返回得到空页面，因此就会出现上述错误。程序中wating是采取的等待重试，也可以添加动态ip等其他反爬虫策略。

**Comment by YuleZhang** [comment]
已解决
